// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcTestClient is the client API for GrpcTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcTestClient interface {
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type grpcTestClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcTestClient(cc grpc.ClientConnInterface) GrpcTestClient {
	return &grpcTestClient{cc}
}

 func (c *grpcTestClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/common.GrpcTest/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcTestServer is the server API for GrpcTest service.
// All implementations must embed UnimplementedGrpcTestServer
// for forward compatibility
type GrpcTestServer interface {
	Test(context.Context, *TestRequest) (*TestResponse, error)
	mustEmbedUnimplementedGrpcTestServer()
}

// UnimplementedGrpcTestServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcTestServer struct {
}

func (UnimplementedGrpcTestServer) Test(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedGrpcTestServer) mustEmbedUnimplementedGrpcTestServer() {}

// UnsafeGrpcTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcTestServer will
// result in compilation errors.
type UnsafeGrpcTestServer interface {
	mustEmbedUnimplementedGrpcTestServer()
}

func RegisterGrpcTestServer(s grpc.ServiceRegistrar, srv GrpcTestServer) {
	s.RegisterService(&GrpcTest_ServiceDesc, srv)
}

func _GrpcTest_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcTestServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.GrpcTest/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcTestServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcTest_ServiceDesc is the grpc.ServiceDesc for GrpcTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.GrpcTest",
	HandlerType: (*GrpcTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _GrpcTest_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpctst.proto",
}
